Rewrite the bootstrap script.
Signed-off-by: Jason Lynch <jason@calindora.com>

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -1,156 +1,149 @@
 #!/usr/bin/env bash
-#
-# bootstrap installs things.
+#-------------------------------------------------------------------------------
 
-cd "$(dirname "$0")/.."
-DOTFILES_ROOT=$(pwd -P)
-
-set -e
-
-echo ''
+#-------------------------------------------------------------------------------
+# Output Functions
+#-------------------------------------------------------------------------------
 
 info () {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+	printf "\r  [ \e[0;34m..\e[0m ] $1\n"
 }
 
-user () {
-  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+userinput () {
+	printf "\r  [ \e[0;33m??\e[0m ] $1 "
 }
 
 success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+	printf "\r\e[2K  [ \e[0;32mOK\e[0m ] $1\n"
 }
 
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+	printf "\r\e[2K  [\e[0;31mFAIL\e[0m] $1\n"
+	echo
+	exit
+}
+
+#-------------------------------------------------------------------------------
+# General Functions
+#-------------------------------------------------------------------------------
+
+install_dotfiles () {
+	info 'Installing dotfiles...'
+
+	local overwrite_all=false
+	local backup_all=false
+	local skip_all=false
+
+	for src in $(find -H "$DOTFILES_ROOT" -name '*.symlink' -not -path '*.git*') ; do
+		dst="$HOME/.$(basename "${src%.*}")"
+		link_file "$src" "$dst"
+	done
+}
+
+link_file () {
+	local src=$1
+	local dst=$2
+
+	local overwrite=
+	local backup=
+	local skip=
+
+	local action=
+
+	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ] ; then
+		if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ] ; then
+			local current_src="$(readlink -f $dst)"
+
+			if [ "$current_src" == "$src" ]; then
+				skip=true
+			else
+				userinput "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+		[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+				read -n 1 action
+
+				case "$action" in
+					o)
+						overwrite=true
+						;;
+					O)
+						overwrite_all=true
+						;;
+					b)
+						backup=true
+						;;
+					B)
+						backup_all=true
+						;;
+					s)
+						skip=true
+						;;
+					S)
+						skip_all=true
+						;;
+					*)
+						;;
+				esac
+			fi
+		fi
+
+		overwrite=${overwrite:-$overwrite_all}
+		backup=${backup:-$backup_all}
+		skip=${skip:-$skip_all}
+
+		if [ "$overwrite" == "true" ] ; then
+			rm -rf "$dst"
+			success "Removed $dst"
+		fi
+
+		if [ "$backup" == "true" ] ; then
+			mv "$dst" "${dst}.backup"
+			success "Moved $dst to ${dst}.backup"
+		fi
+
+		if [ "$skip" == "true" ] ; then
+			success "Skipped $src"
+		fi
+	fi
+
+	if [ "$skip" != "true" ] ; then
+		ln -sr "$src" "$dst"
+		success "Symlinked $dst -> $src"
+	fi
 }
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
-    info 'setup gitconfig'
+	GITCONFIG_LOCAL=topics/git/gitconfig.local.symlink
 
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
+	if ! [ -f $GITCONFIG_LOCAL ] ; then
+		info 'Configuring git...'
 
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
+		userinput ' * What is your GitHub author name?'
+		read -e git_authorname
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+		userinput ' * What is your GitHub author email address?'
+		read -e git_authoremail
 
-    success 'gitconfig'
-  fi
+		cat <<EOF > $GITCONFIG_LOCAL
+[user]
+	name = $git_authorname
+	email = $git_authoremail
+EOF
+
+		success 'git configured!'
+	fi
 }
 
+#-------------------------------------------------------------------------------
+# Main Execution
+#-------------------------------------------------------------------------------
 
-link_file () {
-  local src=$1 dst=$2
+# Change to the root dotfiles directory.
+cd "$(dirname "$0")/.."
+DOTFILES_ROOT=$(pwd -P)
 
-  local overwrite= backup= skip=
-  local action=
+# Exit immediately if a command returns a non-zero status.
+set -e
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
-
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
-      then
-
-        skip=true;
-
-      else
-
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
-        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
-
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-
-      fi
-
-    fi
-
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
-
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
-
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
-
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
-    fi
-  fi
-
-  if [ "$skip" != "true" ]  # "false" or empty
-  then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
-}
-
-install_dotfiles () {
-  info 'installing dotfiles'
-
-  local overwrite_all=false backup_all=false skip_all=false
-
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
-  do
-    dst="$HOME/.$(basename "${src%.*}")"
-    link_file "$src" "$dst"
-  done
-}
-
+# Do the actual setup.
 setup_gitconfig
 install_dotfiles
-
-# If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot > /tmp/dotfiles-dot 2>&1
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
-
-echo ''
-echo '  All installed!'
